### ISSUE TITLE
Intra-wiki links are not properly rendered

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#102]
Reported by Brian N this morning: 
"...the internal links don't work in the newly posted articles as well as in some of the older ones! (An example of a newer article is e.g. in https://encyclopedia.densho.org/Verne%20Austin; an older one is https://encyclopedia.densho.org/Hideo%20Date. One for which the links do work is https://encyclopedia.densho.org/Citizen%2013660%20(book).) I can't figure out what's going on, since the links do work in the wiki, and the coding is identical with the links that do and don't work."

See, for example: https://encyclopedia.densho.org/Verne%20Austin

In the first paragraph, the intra-wiki link to the Tule Lake article appears as: 

`https://encyclopedia.densho.org/index.php?title=Tulelake_(detention_facility)`

where it should be properly formatted as:

`https://encyclopedia.densho.org/Tulelake_(detention_facility)`

This appears to be happening in newly published articles only.

It is likely that this has related issues in https://github.com/denshoproject/encyc-core and/or https://github.com/denshoproject/encyc-mw

**Comment by gjost** [comment]
My first thought is that this is due to a config file change in `encyc-mw` when we upgraded MediaWiki.

**Comment by gjost** [comment]
Fixed URLs in `ansible-colo` commit `986512d`.  Pulled change to colo and ran `encycedit` playbook.  
Links in `https://encyclopedia.densho.org/Verne%20Austin` are now correct.

`encyc articles` updating has been disable for now because some pages updated in dev environment are having problems with images.
