### ISSUE TITLE
Articles not appearing in author's page index

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#103]
Brian N. reported that the author page of one of the contributors, Jonathan van Haremelen, is missing several published articles.

See: https://encyclopedia.densho.org/authors/Jonathan%20van%20Harmelen/

These articles are published and **do** appear in production:
- Eugene Rostow articles
- Gannon Committee
- Tenney Committee

Published, but **do not** appear in production
- Hotel Whitcomb
- Los Angeles County Jail (detention facility)
- Harvey Itano

Editors' mediawiki view of article that shows up in authors index:
https://editors.densho.org/index.php?title=Verne_Austin&action=edit

`AuthorsByline` macro:
`{{ AuthorByline |
BylineText= [[Jonathan van Harmelen]], UC Santa Cruz |
CitationAuthor=Harmelen, Jonathan van}}`

Editors' mediawiki view of article that does not show up in authors index:
https://editors.densho.org/index.php?title=Hotel_Whitcomb&action=edit

`AuthorsByline` macro:
`{{ AuthorByline |
BylineText= [[Jonathan van Harmelen]], UC Santa Cruz |
CitationAuthor=Harmelen, Jonathan van}}`

- Macros appear to be identical
- Both articles were published 3 November 2020
- Still looking for other examples of behavior

May be related to issues with publish functionality in https://github.com/denshoproject/encyc-core

**Comment by gjost** [comment]
This error occurs while publishing articles (`encyc articles`):
```
...
2020-11-11 09:21:20.278609 1193/1524 G. Gordon Brown
2020-11-11 09:21:20.621475 1194/1524 Marvin Opler
ERROR:root:Niiya. Brian
ERROR:root:mediawiki.find_author_info
ERROR:root:ValueError: too many values to unpack
2020-11-11 09:21:21.026379 1195/1524 Music in camp
...
```

**Comment by gjost** [comment]
I'm seeing all of the following on [the author's page](https://encyclopedia.densho.org/authors/Jonathan%20van%20Harmelen/) and all the links work.
- Eugene Rostow articles
- Gannon Committee
- Tenney Committee
- Hotel Whitcomb
- Los Angeles County Jail (detention facility)
- Harvey Itano
