### ISSUE TITLE
ui: Change map links to point at new Sites of Shame 

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#104]
All nav links pointing to encyclopedia.densho.org/map should be repointed at maps.densho.org/sitesofshame. 

The links should:

1.  open in a new window, and 
2. have a visual indicator that it leaves the encyclopedia site (can use the external link css style)

IMPORTANT: SHOULD NOT BE DEPLOYED BEFORE 7/15/2021

**Comment by gjost** [comment]
Link repointed in `encyc-front` `develop` branch commit `9a65d33`.

**Comment by gjost** [comment]
Offsite link marker added in `encyc-front` `develop` branch commit `4c47637`.
Marker uses font glyph added in `encyc-front-assets` `master` branch commit `b523cc2`.
