### ISSUE TITLE
ui: Offsite link indicator font missing

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#106]
The FA icon gylph used to mark offsite links is missing. The url throws a 404:

https://encyclopedia.densho.org/front/static/fonts/fontawesome-webfont.woff2?v=4.4.0

Related to: https://github.com/denshoproject/encyc-front/issues/104

**Comment by gjost** [comment]
Note that this file is present and is v4.4.0.  https://encyclopedia.densho.org/front/static/css/font-awesome.css

**Comment by gjost** [comment]
Added the font file in `encyc-front-assets` `master`-branch commit `02c4e06`, which is installed on encycstage.
