### ISSUE TITLE
"About the Encyclopedia" page is included in the "A-Z" browse page

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#111]
The "About the Encyclopedia" page text appears as an article in the A-Z article index.

https://encyclopedia.densho.org/About%20the%20Encyclopedia

**Comment by gjost** [comment]
Can't we just mark it as unpublished in MediaWiki?

**Comment by gjost** [comment]
I can't see a way to solve this programatically except to add an exclude list to the functions in `encyc-core` that get titles from MediaWiki.  I can do this, but do you want me spending cycles on this?  It seems easier to just remove that page from MediaWiki or mark it unpublished.
