### ISSUE TITLE
Add new Google Tag code

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#113]
Add Google Tag Manager snippets to base templates

**Comment by GeoffFroh** [comment]
Implemented in d84f66fe4bbf65e6bf00e00c8fba2bafd077adb5

**Comment by GeoffFroh** [comment]
@gjost: please merge to `master`, deploy, and then close this issue

**Comment by gjost** [comment]
Merged, pushed, and pulled in colo

**Comment by gjost** [comment]
Oops, I updated ddr-public and closed this issue by mistake. Will get this in a bit
