### ISSUE TITLE
Copyright date on homepage not updated

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#118]
Copyright date in the footer of  homepage (`index.html`) is not generated dynamically. Because the template does not inherit from `base.html`, we forgot to change it.

**Comment by GeoffFroh** [comment]
Fixed in 39b3c07c94bad2c28fb316413597e06d86ac7080

@gjost - please merge in `master` and push to production when convenient (no big rush...)

**Comment by gjost** [comment]
Merged and deployed.  I also did a quick `ack -Q "&copy;"` in the folder where all my dev code lives and `encycfront` was the only project that had the old hard-coded date.
