### ISSUE TITLE
API: bandwidth throttling

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#61]
Request-throttling: Access to the REST API is currently completely open, with no use restrictions. The API should be openly-accessible to anonymous users, but cap daily requests to a reasonable number. 10K?

http://www.django-rest-framework.org/api-guide/authentication/

Seealso
https://github.com/densho/encyc-rg/issues/64
https://github.com/densho/ddr-public/issues/62
https://github.com/densho/ddr-idservice/issues/9

**Comment by gjost** [comment]
Created separate issue for token-based auth: https://github.com/densho/encyc-front/issues/63

**Comment by GeoffFroh** [comment]
Let's set the limit to 500/day

**Comment by gjost** [comment]
API throttle set in `ansible-colo` commit `c5d1f78`.
