### ISSUE TITLE
Some older source detail page download urls are malformed

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#72]
Some download links on `sources` detail pages are malformed. For example, 
this source:

`https://encyclopedia.densho.org/sources/en-denshopd-i35-00428-1/`

Has this download url:

`https://encyclopedia.densho.org/media/1/1422/en-denshopd-i35-00428-1.pdf`

While the actual asset is at:

`https://encyclopedia.densho.org/media/encyc-psms/en-denshopd-i35-00428-1.pdf`

This may be b/c older sources added through PSMS used a different schema for links to the media server and DDR app.

(Note that the displayed link to the original DDR item is also not correct:

`http://ddr.densho.org/ddr/densho/35/428/`

But does resolve correctly -- maybe by url rewriting in the `ddr-public` app?)

**Comment by gjost** [comment]
Yesterday when I looked at the problem it seemed like only PDFs were affected.  I pushed a new `encycfront-master_2.5.8~deb9` package yesterday with a band-aid fix.

**Comment by gjost** [comment]
Yesterday @GeoffFroh reported that PSMS is throwing an error.  See [encyc-psms/issues/12](https://github.com/densho/encyc-psms/issues/12).
