### ISSUE TITLE
"From the DDR" page "see more items" link is malformed

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#88]
The "From the DDR" page template has a "See more items" link (at: `https://github.com/densho/encyc-front/blob/master/front/wikiprox/templates/wikiprox/related-ddr.html#L81`) that is supposed to go to the connected topic page in the ddr-public app; however, the link is malformed, including the extra text `topics-` in the url.

See, for example:

https://encyclopedia.densho.org/ddr/Japanese%20American%20World%20War%20II%20military%20service%20memorials/

The "See more items" link at the bottom of the page is:

`https://ddr.densho.org/browse/topics/topics-118/`

but should be:

`https://ddr.densho.org/browse/topics/118/`

**Comment by GeoffFroh** [comment]
The template (https://github.com/densho/encyc-front/blob/master/front/wikiprox/templates/wikiprox/related-ddr.html) is rendering the var: `{{ term.ddr_topic_url }}` so the problem may be in how `encyc-core` indexes the article into the ES backend. But it might be good enough to fix with simple string replacement in the template since that data may be used elsewhere(?)

**Comment by gjost** [comment]
Fixed in `encyc-front` commit `4688ffd` for package `encycfront-master_4.0.3~deb9`.
