### ISSUE TITLE
Filesize information always reported as "(0 bytes)" on Source detail pages

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#92]
The filesize info that appears in the download link for the images on the Source detail pages is always "(0 bytes)". 

See, for example:

https://encycstage.densho.org/sources/en-denshopd-p159-00002-1/

Could be a data problem, but not very important anyways. Should just be removed from template altogether.

**Comment by gjost** [comment]
Looks like the `original_size` field in Elasticsearch is blank.  This is really an `encyc-core` issue.

**Comment by gjost** [comment]
The current PSMS API does not surface the `original_size` field:
https://psms.densho.org/api/2.0/sources/

**Comment by gjost** [comment]
Mitigation in `encyc-front` commit `f5146b2` for package `encycfront-master_4.1.2~deb10`.  If `Source.original_size` is blank then file size is just not printed at all.  The real fix will come when `encyc-psms` is updated to include `original_size` in the API.
