### ISSUE TITLE
Paths to articles without trailing slashes fail

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#93]
NOTE: This is a regression error found in d446e4796018f0154421aba6d595f9c9da4a71fc. The behavior is not present in the last `master` production package

When the trailing slash is missing from article urls, the path is not found in `front.urls`. 

This fails:

https://encycstage.densho.org/Manzanar

This works:

https://encycstage.densho.org/Manzanar/

**Comment by gjost** [comment]
I'm aware of this one -- it came up in my work on encyc-rg this morning.  I agree it's a bad one.  I think something changed in the way Django handles trailing slashes because it used to not be a problem.

I have a fix in encycrg that should take care of this.  I'll have to add the same fix to encycfr0nt

**Comment by gjost** [comment]
Fixed in `encyc-front` commit `98d7ecf` for package `encycfront-master_4.1.1~deb10`.

**Comment by GeoffFroh** [comment]
`urls.py` should support paths with a trailing slash *and* without a trailing slash.

**Comment by GeoffFroh** [comment]
Looks like this can be controlled through the app settings using the `APPEND_SLASH` var. See: https://docs.djangoproject.com/en/3.0/ref/settings/#append-slash

(Docs say that it is `True` by default; but maybe we need to declare it explicitly?)

**Comment by gjost** [comment]
Fixed in `encyc-front` commit `80aa5f7` for package `encycfront-master_4.1.2~deb10`.

**Comment by pkikawa** [comment]
path successfully found from URLs without trailing slash 👍
