### ISSUE TITLE
sitemaps.xml throws 500 error from webui

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-front#96]
This was working at some point? 

https://github.com/denshoproject/encyc-front/blob/master/front/wikiprox/sitemaps.py

**Comment by gjost** [comment]
Fixed in `encyc-front` `develop` branch commit `7792012`. Changes pulled to `encycstage.densho.org`.

Note that change requires updating the database to set the domain name:
```
from django.contrib.sites.models import Site
s = Site.objects.get(id=1)
s.name = "Densho Encyclopedia"
s.domain = 'encyclopedia.densho.org'
s.save()
```
The database change was performed on both `encycstage` and production.
